name: naw3ia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_expandable_fab: ^2.5.1
  flutter_iconly: ^1.0.2
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^13.0.0
  html: ^0.15.4
  http: ^1.2.0
  iconify_flutter: ^0.0.7
  intro_screen_onboarding_flutter: ^1.0.0
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/translations/ar.json
    - assets/translations/en.json

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
