name: smart_naw3ia
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # For handling local and push notifications with advanced features
  awesome_notifications: ^0.9.2
  
  # Default Flutter icons
  cupertino_icons: ^1.0.2
  
  # Flutter SDK
  flutter:
    sdk: flutter
  
  # State management solution using BLoC pattern
  flutter_bloc: ^8.1.3
  
  # For creating expandable floating action buttons
  flutter_expandable_fab: ^2.5.1
  
  # Collection of beautiful icons
  font_awesome_flutter: ^10.8.0
  flutter_iconly: ^1.0.2
  
  # For handling app localization and translations
  flutter_localization: ^0.3.2
  
  # Flutter's built-in localization support
  flutter_localizations:
    sdk: flutter
  
  # For responsive UI design across different screen sizes
  flutter_screenutil: ^5.9.0
  
  # For secure storage of sensitive data
  flutter_secure_storage: ^9.2.4
  
  # For adding beautiful animations to lists and grids
  flutter_staggered_animations: ^1.1.1

  # For declarative routing and navigation
  go_router: ^13.0.0
  
  # For generating app icons for different platforms
  icons_launcher: ^3.0.1
  
  # For internationalization and localization
  intl: 0.19.0
  
  # For creating beautiful onboarding screens
  intro_screen_onboarding_flutter: ^1.0.0
  
  # For adding Lottie animations
  lottie: ^3.3.1
  
  # For simple key-value storage
  shared_preferences: ^2.5.3
  
  # For implementing calendar functionality
  table_calendar: ^3.0.9
  
  # For launching URLs and handling deep links
  url_launcher: ^6.2.4

dev_dependencies:
  # For enforcing Flutter coding standards
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/translations/ar.json
    - assets/translations/en.json

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

icons_launcher:
  image_path: "assets/images/light_mode_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
